# Generated by Django 4.1.1 on 2022-10-05 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_teacher_alter_student_managers_remove_student_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 10, 5)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default=datetime.date(2022, 10, 5), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.CharField(default=datetime.date(2022, 10, 5), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
