# Generated by Django 4.1.1 on 2022-10-15 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_student_teacher'),
        ('main_app', '0003_coursetaken_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.assignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='courseAssignments',
            field=models.ManyToManyField(related_name='assignments', through='main_app.CourseAssignment', to='main_app.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='studentAssignments',
            field=models.ManyToManyField(related_name='assignments', through='main_app.StudentAssignment', to='auth.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacherAssignments',
            field=models.ManyToManyField(related_name='assignments', through='main_app.TeacherAssignment', to='auth.teacher'),
        ),
    ]
