# Generated by Django 4.1.1 on 2022-10-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_teacher_description_alter_user_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('main_app.student', 'Can add user')], 'verbose_name_plural': 'Teacher'},
        ),
    ]
