# Generated by Django 4.1.1 on 2022-10-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_student_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('main_app.student', 'FFFFFFFFFFFFFFFFFFff')], 'verbose_name_plural': 'Teacher'},
        ),
    ]
