# Generated by Django 4.1.1 on 2022-10-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_teacher_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
