# Generated by Django 4.1.1 on 2022-10-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
